
name: build of android app


env:
  main_project_module: app

on:
  pull_request:
    branches: [main]
    paths:
    - 'Android_Phone_App/**'  
  workflow_dispatch:   #for manual run
          
jobs:
  build_app:
    name: Build android apk file
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set current date as env variable
      run: echo "date_today=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
    - name: Set repository name as env variable
      run: echo "repository_name=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
    - name: Move to phone app directory
      run: cd Android_Phone_App
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle #also runs gradle tests
      run: ./gradlew build
    - name: Upload APK Debug - ${{ env.repository_name }}
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.date_today }}- ${{ env.repository_name }} - generated APK debug
        path: ${{ env.main_project_module }}/build/outputs/apk/debug/
